caching:
  rules:
    - description: "Static assets"
      match:
        url: "*.(?:jpg|jpeg|gif|png|ico|css|js)"
      settings:
        edge_cache_ttl: 2592000  # 30 days
        browser_cache_ttl: 86400  # 1 day
        cache_level: "cache_everything"
        
    - description: "API responses"
      match:
        url: "/api/*"
      settings:
        edge_cache_ttl: 30
        cache_by_device_type: true
        cache_deception_armor: true
        
    - description: "Dynamic content"
      match:
        url: "/*"
      settings:
        edge_cache_ttl: 1800  # 30 minutes
        respect_strong_etags: true
        serve_stale_content: true 