name: Build Tests

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]

jobs:
  test-builds:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install Dependencies
        working-directory: ./frontend
        run: npm ci
        
      - name: Test Development Build
        working-directory: ./frontend
        run: |
          npm run build
          npm run test
          
      - name: Test Production Build
        working-directory: ./frontend
        env:
          NODE_ENV: production
        run: |
          npm run build
          npm run test
          
      - name: Check Bundle Size
        working-directory: ./frontend
        run: npm run analyze 